# MockMach -- sounds like mäk mäk (which rhymes with what a chiken would say)
title: "Derek Nutile"

# replace with the mockups main email address
email: hello@dereknutile.com

# brief description for the site
description: "Developer/Polyglot"

# one line short description for the site
tagline: "code | ship | rinse | repeat"

# leave empty unless you need to store the mockup in a subfolder
# don't use a trailing slash
baseurl: ""

# replace with the domain of the mockup
url: "http://dereknutile.com/"

# site favicon
favicon: "/assets/ico/favicon.png"

# contacts
phone: "15036571842"
phone-string: "503-657-1842"
facebook-username: "dereknutile"
twitter-username: "dereknutile"
google-plus-username: "dereknutile"

# analytic settings
google-analytics: "UA-15896808-1"

# Jekyll build settings
markdown: kramdown
permalink: pretty
